name: CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          TARGET_REPO_GITHUB_PAT: ${{ secrets.TARGET_REPO_GITHUB_PAT }}
        run: |
          COMMIT_COMMENT=$(git log -1 --pretty=format:"%s")
          git clone https://x-access-token:${TARGET_REPO_GITHUB_PAT}@github.com/tanayseven/tanayseven.github.io.git
          rsync -av --delete public/ tanayseven.github.io/
          cd tanayseven.github.io/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: build artifacts for '${COMMIT_COMMENT}' [skip ci]"
          git push origin main
